using MessageFlow.Domain.Enums;
using MessageFlow.Domain.Exceptions;

namespace MessageFlow.Domain.AI;

/// <summary>
/// Structured query generated by AI from natural language.
/// Never executed as raw SQL — translated to safe EF Core queries.
/// </summary>
public sealed record DatasetQuery
{
    public DatasetQueryAction Action { get; init; }
    public string? TargetColumn { get; init; }
    public IReadOnlyList<DatasetQueryFilter> Filters { get; init; } = [];
    public string? GroupByColumn { get; init; }
    public int? Limit { get; init; }

    public static DatasetQuery Create(
        DatasetQueryAction action,
        string? targetColumn = null,
        IReadOnlyList<DatasetQueryFilter>? filters = null,
        string? groupByColumn = null,
        int? limit = null)
    {
        if (action is DatasetQueryAction.Sum or DatasetQueryAction.Average
            or DatasetQueryAction.Min or DatasetQueryAction.Max
            && string.IsNullOrWhiteSpace(targetColumn))
        {
            throw new DomainException(
                $"Action '{action}' requires a target column.");
        }

        if (action == DatasetQueryAction.GroupBy && string.IsNullOrWhiteSpace(groupByColumn))
        {
            throw new DomainException(
                "GroupBy action requires a groupByColumn.");
        }

        if (limit is < 1 or > 1000)
        {
            throw new DomainException(
                "Limit must be between 1 and 1000.");
        }

        return new DatasetQuery
        {
            Action = action,
            TargetColumn = targetColumn,
            Filters = filters ?? [],
            GroupByColumn = groupByColumn,
            Limit = limit,
        };
    }
}

/// <summary>
/// Filter condition for dataset query.
/// </summary>
public sealed record DatasetQueryFilter
{
    public string Column { get; init; } = default!;
    public DatasetQueryOperator Operator { get; init; }
    public string? Value { get; init; }

    public static DatasetQueryFilter Create(string column, DatasetQueryOperator op, string? value = null)
    {
        if (string.IsNullOrWhiteSpace(column))
        {
            throw new DomainException("Filter column is required.");
        }

        if (op is DatasetQueryOperator.IsNull or DatasetQueryOperator.IsNotNull)
        {
            return new DatasetQueryFilter { Column = column, Operator = op, Value = null };
        }

        if (op != DatasetQueryOperator.Contains && string.IsNullOrWhiteSpace(value))
        {
            throw new DomainException(
                $"Filter operator '{op}' requires a value.");
        }

        return new DatasetQueryFilter { Column = column, Operator = op, Value = value };
    }
}

/// <summary>
/// Actions that can be performed on dataset data.
/// </summary>
public enum DatasetQueryAction
{
    Count = 1,
    Sum = 2,
    Average = 3,
    Min = 4,
    Max = 5,
    GroupBy = 6,
    Top = 7,
    Search = 8
}

/// <summary>
/// Operators for dataset query filters.
/// </summary>
public enum DatasetQueryOperator
{
    Equals = 1,
    NotEquals = 2,
    Contains = 3,
    GreaterThan = 4,
    GreaterThanOrEqual = 5,
    LessThan = 6,
    LessThanOrEqual = 7,
    IsNull = 8,
    IsNotNull = 9
}

/// <summary>
/// Result from dataset query execution.
/// </summary>
public sealed record DatasetQueryResult
{
    public string Answer { get; init; } = default!;
    public DatasetQuery Query { get; init; } = default!;
    public object? Data { get; init; }
    public IReadOnlyList<DatasetRowDto>? Rows { get; init; }
}

/// <summary>
/// Row data for query results.
/// </summary>
public sealed record DatasetRowDto(
    Guid Id,
    long RowNumber,
    IReadOnlyDictionary<string, string?> Values);

/// <summary>
/// Group result for GroupBy queries.
/// </summary>
public sealed record GroupResult(
    string Key,
    long Count);
